export const books = [
  {
    name: "COPYBOOK EXAMPLE 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed bibendum tortor tortor, vitae viverra ante accumsan hendrerit. Donec eu nunc.",
    content: "  * -------------------------------------------------------------*\n  *   Name = EYUL2400                                            *\n  *   Format Name = EMASSTRT                                     *\n  *   Version = 0001                                             *\n  *   Status = CPSMREL(0310)                                     *\n  *   Function = Base Table Structure generator                  *\n  *   Format definition for this element = EMASSTRT              *\n  *   Valid Operations = None                                    *\n  *   Valid Actions = None                                       *\n  * -------------------------------------------------------------*\n   01 EMASSTRT.\n  * Notify CICS System Start Event\n     02 CMASNAME       PIC X(0008).\n  * CMAS Name\n     02 PLEXNAME       PIC X(0008).\n  * CICSPlex Name\n     02 CSYSNAME       PIC X(0008).\n  * CICS System Name\n     02 MON-SPEC       PIC X(0008).\n  * Monitor Spec Name\n     02 RTA-SPEC       PIC X(0008).\n  * Real Time Analysis Spec Name\n     02 WLM-SPEC       PIC X(0008).\n  * Work Load Manager Spec Name\n     02 STATUS-R       PIC X(0001).\n  * Status                              -- RESERVED WORD --\n       88 LOCAL        VALUE X'80'.\n  * Local MAS\n       88 REMOTE       VALUE X'40'.\n  * Remote MAS\n     02 DYNROUTE       PIC X(0001).\n  * Dynamic Routing Mode\n       88 ACTIVE       VALUE X'01'.\n  * Routing ACTIVE\n       88 SUSPEND      VALUE X'02'.\n  * Routing SUSPENDED\n     02 DYNTYPE        PIC X(0003).\n  * Dynamic Routing Type\n       88 WLMTOR       VALUE 'TOR'.\n  * Routing TOR\n       88 WLMAOR       VALUE 'AOR'.\n  * Routing AOR\n     02 DESC           PIC X(0030).\n  * Description\n     02 CSYSAPPL       PIC X(0008).\n  * CICS System VTAM APPLID\n     02 EYU-RSV0015    PIC X(0005)."
  },
  {
    name: "COPYBOOK EXAMPLE 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id congue augue, nec lacinia ante. Etiam eu arcu ut tellus.",
    content: "01 MY-RECORD. \n 05 CLAIM-NUMBER             PIC X(19). \n 05 ADMISSION-DATE           PACKED-DECIMAL PIC S9(7). \n 05 FROM-DATE                PACKED-DECIMAL PIC S9(7). \n 05 THRU-DATE                PACKED-DECIMAL PIC S9(7). \n 05 DISCHARGE-DATE           PACKED-DECIMAL PIC S9(7). \n 05 FULL-DAYS                PACKED-DECIMAL PIC S9(5). \n 05 COINSURANCE-DAYS         BINARY         PIC 9(4). \n 05 LIFETIME-RES-DAYS        BINARY         PIC 9(6). \n 05 INTERMEDIARY-NUM         BINARY         PIC 9(10). \n 05 PROVIDER                                PIC X(13). \n 05 INPATIENT-DED            PACKED-DECIMAL PIC S9(4)V99.\n 05 BLOOD-DED                PACKED-DECIMAL PIC S9(4)V99.\n 05 TOTAL-CHARGES      PIC S9(7)V99 DISPLAY SIGN LEADING.\n 05 PATIENT-STATUS                          PIC X(2). \n 05 BLOOD-PINTS-FURNISHED    BINARY         PIC 9(5). \n 05 BLOOD-PINTS-REPLACED     BINARY         PIC 9(4). \n 05 SEQUENCE-COUNTER         BINARY         PIC 9(3). \n 05 TRANSACTION-IND                         PIC 9. \n 05 BILL-SOURCE                             PIC 9. \n 05 BENEFITS-EXHAUST-IND                    PIC 9. \n 05 BENEFITS-PAY-IND                        PIC 9. \n 05 AUTO-ADJUSTMENT-IND                     PIC X. \n 05 INTERMEDIARY-CTRL-NUM                   PIC X(23)."
  }
]